---
abstract: 'Tests of sequences for runs, joins, bunches, turns, doublets, trinomes, potential energy, etc.'
author:
  - 'Roderick Garton <rgarton@cpan.org>'
build_requires:
  Scalar::Util: 1.18
  Statistics::Data: 0.02
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3624'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-Sequences
provides:
  Statistics::Sequences:
    file: lib/Statistics/Sequences.pm
    version: 0.11
requires:
  Scalar::Util: 1.18
  Statistics::Data: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.11
